### ISSUE TITLE
Bars are transparent when all tested variables are significant

### ISSUE THREAD

**Issue by LanderDC** [raeslab/RLdbRDA#3] opened 2024-02-29 12:35 UTC
Hi, 
I noticed that when all my metadata variables had a significant effect on the community composition, all the bars in the plot resulting from `plot_dbrda` were transparent. My guess is that the code below will set the alpha to 0.75 if all `significant` values in the `plot_data` df are the same:
https://github.com/raeslab/RLdbRDA/blob/d0ce366c7d4bcbcca535a4cb62c4d5c854778986/R/rldbrda.R#L332 

My fix was to include an `if else` statement to determine which `scale_alpha_continuous` should be used, but there might be better ways to do this.

```r
plot_dbrda <- function(plot_data) {
    if (length(unique(plot_data$significant)) > 1) {
      alpha_scale <- scale_alpha_continuous(range = c(0.5, 1))
    } else if (unique(plot_data$significant) == 1) {
      alpha_scale <- scale_alpha_continuous(range = 1)
    } else {
      alpha_scale <- scale_alpha_continuous(range = 0.5)
    }
    
    ggplot(data = plot_data, aes(x = value, y = rowname, fill = variable)) +
      geom_bar(aes(alpha = significant), stat = 'identity', position = position_dodge2()) +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 0, hjust = 1)) +
      xlab('Effect size') +
      ylab('Feature') +
      labs(fill = "", alpha = "") + # Hide title of the legend and alpha legend
      guides(alpha = "none") + # Hide alpha legend
      scale_fill_manual(values = c("#60A68B", "#1F4068"),
                        labels = c(bquote(R^2), bquote('Cumulative' ~ R^2))) +
      alpha_scale
  }
```

**Comment by sepro** [comment] 2024-02-29 16:00
Thanks for reaching out and spotting an edge-case I haven't encountered yet. You're also correct about the cause, though there is a slightly more elegant way to fix this using the `limits` parameter of `scale_alpha_continuous`.

Fixed in f261e1b0a322e84d59bb6b80b2c5ae1855f42888

**Closed as completed by sepro** 2024-02-29 16:00 UTC
